import assert from 'node:assert/strict';
import { OpenAiResponsesTextModelAdapter } from '../cms/pipeline/adapters/openAiResponsesTextModelAdapter.js';

const responseValue = {
  displayName: 'OpenAI Test Fighter',
  description: 'A structured-output fighter generated by the fake OpenAI Responses client.',
  stats: {
    walkForwardSpeed: 3.2,
    walkBackSpeed: 2.1,
    jumpVelocity: 11,
    jumpForwardVelocity: 4,
    jumpBackVelocity: 3,
    gravity: 0.55,
    maxFallSpeed: 12,
    maxHealth: 1125,
  },
  sprite: {
    basePath: '/fighters/openai_test',
    scale: 0.55,
    frameCounts: {
      base: 6,
      punch: 6,
      kick: 6,
      special_1: 6,
      special_2: 6,
    },
  },
  moves: [
    move('light_punch', 'Light Punch', 'punch'),
    move('heavy_punch', 'Heavy Punch', 'punch'),
    move('crouch_low_kick', 'Low Kick', 'kick'),
    move('fireball', 'Signature Projectile', 'special_1'),
  ],
};

let capturedRequest;
const adapter = new OpenAiResponsesTextModelAdapter({
  apiKey: 'test-key',
  model: 'gpt-test',
  fetch: async (url, options) => {
    capturedRequest = {
      url,
      body: JSON.parse(options.body),
      authorization: options.headers.authorization,
    };
    return new Response(JSON.stringify({
      id: 'resp_test_text_model',
      model: 'gpt-test',
      output_text: JSON.stringify(responseValue),
      output: [],
    }), {
      status: 200,
      headers: { 'content-type': 'application/json' },
    });
  },
});

const health = await adapter.healthCheck();
assert.equal(health.status, 'ok');

const result = await adapter.completeStructured({
  task: 'character-content-draft',
  schemaName: 'CharacterContentDraft',
  schemaVersion: 1,
  input: {
    characterId: 'openai_test',
    brief: 'A test fighter for structured output.',
  },
});

assert.equal(result.provider, 'openai');
assert.equal(result.model, 'gpt-test');
assert.equal(result.promptRef, 'resp_test_text_model');
assert.equal(result.value.displayName, 'OpenAI Test Fighter');
assert.equal(result.value.stats.maxHealth, 1125);
assert.equal(result.value.moves[0].phases[0].events.length, 0);

assert.equal(capturedRequest.authorization, 'Bearer test-key');
assert.match(capturedRequest.url, /\/responses$/);
assert.equal(capturedRequest.body.model, 'gpt-test');
assert.equal(capturedRequest.body.text.format.type, 'json_schema');
assert.equal(capturedRequest.body.text.format.name, 'CharacterContentDraft');
assert.equal(capturedRequest.body.text.format.strict, true);
assert.equal(capturedRequest.body.text.format.schema.required.includes('moves'), true);
assert.match(capturedRequest.body.instructions, /Thousand Fighters/);

console.log('OpenAI Responses text model smoke test passed.');

function move(id, displayName, animation) {
  return {
    id,
    displayName,
    description: `${displayName} test move.`,
    animation,
    trigger: { sequence: [] },
    phases: [
      { name: 'startup', frames: 4, events: [] },
      { name: 'active', frames: 4, events: [] },
      { name: 'recovery', frames: 10, events: [] },
    ],
  };
}
